function genBreastXlsReport(analysis, SXAanalysis, info, machineParams, reportName)
global rootdir xlsLineNum

fileName = [reportName, '.xls'];
filePathName = [rootdir, '\debug\', fileName];
calibVer = info.Version;

if xlsLineNum == 1
    sht1Title = {'Machine ID', 'Acquisition ID', 'Date Acquisition', ...
                 'Paddle Size', 'Breast Density', 'Breast Volume', 'Version'};
	sht2Title = {'Machine ID', 'Acquisition ID', 'Date Acquisition', ...
                 'Paddle Size', 'ROI 1', 'ROI 2', 'ROI 3', 'ROI 4', ...
                 'ROI 5', 'ROI 6', 'ROI 7', 'ROI 8', 'ROI 9', ...
                 'Angle rx', 'Angle ry', 'Angle rz', ...
                 'Coord tx', 'Coord ty', 'Coord tz'};
    xlswrite(filePathName, sht1Title, 'SXAresults');
    xlswrite(filePathName, sht2Title, 'SXAstepInfo');
    xlsLineNum = xlsLineNum + 1;
end

%convert date_acquisition from yyyymmdd to mm/dd/yyyy
dateAcqISO = num2str(info.FilmDate);
dateAcqUS = [dateAcqISO(5:6), '/', dateAcqISO(7:8), '/', dateAcqISO(1:4)];

sht1Info = {info.centerlistactivated, info.AcquisitionKey, dateAcqUS, ...
            machineParams.padSize, analysis.DensityPercentage, ...
            SXAanalysis.SXABreastVolumeReal, calibVer(8:end)};
sht2Info = {info.centerlistactivated, info.AcquisitionKey, dateAcqUS, ...
            machineParams.padSize, analysis.roi_valuescorr(1), ...
            analysis.roi_valuescorr(2), analysis.roi_valuescorr(3), ...
            analysis.roi_valuescorr(4), analysis.roi_valuescorr(5), ...
            analysis.roi_valuescorr(6), analysis.roi_valuescorr(7), ...
            analysis.roi_valuescorr(8), analysis.roi_valuescorr(9), ...
            analysis.params(1), analysis.params(2), analysis.params(3), ...
            analysis.params(5), analysis.params(6), analysis.params(4)};

xlswrite(filePathName, sht1Info, 'SXAresults', ['A', num2str(xlsLineNum)]);
xlswrite(filePathName, sht2Info, 'SXAstepInfo', ['A', num2str(xlsLineNum)]);

xlsLineNum = xlsLineNum + 1;
