function genGen3XlsReport(analysis, info, machineParams, reportName)
global rootdir xlsLineNum

fileName = [reportName, '.xls'];
filePathName = [rootdir, '\debug\', fileName];

% if exist(filePathName, 'file')
%     delete(filePathName)
% end

if xlsLineNum == 1
    sht1Title = {'Machine ID', 'Acquisition ID', 'Date Acquisition', ...
                 'Time Acquisition', 'Paddle Size', ...
                 'x0cm_diff', 'y0cm_diff', ...
                 'Source Height', 'Bucky Distance', 'Dark Counts', ...
                 'Thickness Corr', 'rx Corr', 'ry Corr', 'validity flag'};
	sht2Title = {'Machine ID', 'Acquisition ID', 'Date Acquisition', ...
                 'Time Acquisition', 'Paddle Size', ...
                 'thickness', 'kLean', 'km', 'thickness', 'kLean', 'km', ...
                 'thickness', 'kLean', 'km', 'thickness', 'kLean', 'km', ...
                 'thickness', 'kLean', 'km', 'thickness', 'kLean', 'km', ...
                 'thickness', 'kLean', 'km', 'thickness', 'kLean', 'km', ...
                 'thickness', 'kLean', 'km'};
	sht3Title = {'Machine ID', 'Acquisition ID', 'Date Acquisition', ...
                 'Time Acquisition', 'Paddle Size', ...
                 'thickness', 'density', 'correction', 'thickness', 'density', 'correction', ...
                 'thickness', 'density', 'correction', 'thickness', 'density', 'correction', ...
                 'thickness', 'density', 'correction', 'thickness', 'density', 'correction', ...
                 'thickness', 'density', 'correction', 'thickness', 'density', 'correction', ...
                 'thickness', 'density', 'correction'};
    sht4Title = {'Machine ID', 'Acquisition ID', 'Date Acquisition', ...
                 'Time Acquisition', 'Paddle Size', ...
                 'p1 intercept', 'p2 dens', 'p3 dens^2', 'p4 th*dens', 'p5 th*dens^2', ...
                 'Root MSE', 'Dependent Mean', 'Coeff Var', 'R-Squared'};
    sht5Title = {'Machine ID', 'Acquisition ID', 'Date Acquisition', ...
                 'Time Acquisition', 'Paddle Size', ...
                 'WAX_100_6cm', 'WAX_100_4cm', 'WAX_100_2cm', ...
                 'WAX_50_6cm', 'WAX_50_4cm', 'WAX_50_2cm', ...
                 'WAX_0_6cm', 'WAX_0_4cm', 'WAX_0_2cm'};
    xlswrite(filePathName, sht1Title, 'MachineParameters');
    xlswrite(filePathName, sht2Title, 'kTable');
    xlswrite(filePathName, sht3Title, 'QCWAXdensity');
    xlswrite(filePathName, sht4Title, 'DensityFitParams');
    xlswrite(filePathName, sht5Title, 'QCWAXdensityCorrected');
    xlsLineNum = xlsLineNum + 1;
end

%convert date_acquisition from yyyymmdd to mm/dd/yyyy
dateAcqISO = num2str(info.FilmDate);
dateAcqUS = [dateAcqISO(5:6), '/', dateAcqISO(7:8), '/', dateAcqISO(1:4)];

%convert time_acquisition from (h)hmmss to hh:mm:ss
timeAcq = num2str(info.timeAcq);
if length(timeAcq) == 5
    timeAcq = [timeAcq(1), ':', timeAcq(2:3), ':', timeAcq(4:5)];
else
    timeAcq = [timeAcq(1:2), ':', timeAcq(3:4), ':', timeAcq(5:6)];
end

sht1Info = {info.centerlistactivated, info.AcquisitionKey, dateAcqUS, ...
            timeAcq, machineParams.padSize, ...
            analysis.x0cm_diff, analysis.y0cm_diff, ...
            machineParams.source_height, machineParams.bucky_distance, machineParams.dark_counts, ...
            machineParams.th_correction, machineParams.rx_correction, machineParams.ry_correction, machineParams.valFlag};
sht2Info = {info.centerlistactivated, info.AcquisitionKey, dateAcqUS, ...
            timeAcq, machineParams.padSize, ...
            analysis.kTable(1, 1), analysis.kTable(1, 2), analysis.kTable(1, 3), ...
            analysis.kTable(2, 1), analysis.kTable(2, 2), analysis.kTable(2, 3), ...
            analysis.kTable(3, 1), analysis.kTable(3, 2), analysis.kTable(3, 3), ...
            analysis.kTable(4, 1), analysis.kTable(4, 2), analysis.kTable(4, 3), ...
            analysis.kTable(5, 1), analysis.kTable(5, 2), analysis.kTable(5, 3), ...
            analysis.kTable(6, 1), analysis.kTable(6, 2), analysis.kTable(6, 3), ...
            analysis.kTable(7, 1), analysis.kTable(7, 2), analysis.kTable(7, 3), ...
            analysis.kTable(8, 1), analysis.kTable(8, 2), analysis.kTable(8, 3), ...
            analysis.kTable(9, 1), analysis.kTable(9, 2), analysis.kTable(9, 3)};
sht3Info = {info.centerlistactivated, info.AcquisitionKey, dateAcqUS, ...
            timeAcq, machineParams.padSize, ...
            2, analysis.densCorrTable(1, 1, 1), analysis.densCorrTable(2, 1, 1), ...
            2, analysis.densCorrTable(1, 2, 1), analysis.densCorrTable(2, 2, 1), ...
            2, analysis.densCorrTable(1, 3, 1), analysis.densCorrTable(2, 3, 1), ...
            4, analysis.densCorrTable(1, 1, 2), analysis.densCorrTable(2, 1, 2), ...
            4, analysis.densCorrTable(1, 2, 2), analysis.densCorrTable(2, 2, 2), ...
            4, analysis.densCorrTable(1, 3, 2), analysis.densCorrTable(2, 3, 2), ...
            6, analysis.densCorrTable(1, 1, 3), analysis.densCorrTable(2, 1, 3), ...
            6, analysis.densCorrTable(1, 2, 3), analysis.densCorrTable(2, 2, 3), ...
            6, analysis.densCorrTable(1, 3, 3), analysis.densCorrTable(2, 3, 3)};
sht4Info = {info.centerlistactivated, info.AcquisitionKey, dateAcqUS, ...
            info.FilmDate, machineParams.padSize, ...
            analysis.densFitParam(1), analysis.densFitParam(2), ...
            analysis.densFitParam(3), analysis.densFitParam(4), ...
            analysis.densFitParam(5), analysis.densFitAnalysis(1), ...
            analysis.densFitAnalysis(2), analysis.densFitAnalysis(3), ...
            analysis.densFitAnalysis(4)};
sht5Info = {info.centerlistactivated, info.AcquisitionKey, dateAcqUS, ...
            timeAcq, machineParams.padSize, ...
            analysis.densityWaxRoiCorr(1), analysis.densityWaxRoiCorr(2), analysis.densityWaxRoiCorr(3), ...
            analysis.densityWaxRoiCorr(4), analysis.densityWaxRoiCorr(5), analysis.densityWaxRoiCorr(6), ...
            analysis.densityWaxRoiCorr(7), analysis.densityWaxRoiCorr(8), analysis.densityWaxRoiCorr(9)};
xlswrite(filePathName, sht1Info, 'MachineParameters', ['A', num2str(xlsLineNum)]);
xlswrite(filePathName, sht2Info, 'kTable', ['A', num2str(xlsLineNum)]);
xlswrite(filePathName, sht3Info, 'QCWAXdensity', ['A', num2str(xlsLineNum)]);
xlswrite(filePathName, sht4Info, 'DensityFitParams', ['A', num2str(xlsLineNum)]);
xlswrite(filePathName, sht5Info, 'QCWAXdensityCorrected', ['A', num2str(xlsLineNum)]);

xlsLineNum = xlsLineNum + 1;

