function ellipse_testfit()
%Assume the data (x, y, and t) is generated by

t = (0:pi/10:2*pi)';
x = 5 + 4*cos(t) + rand(size(t));
y = 8 + 2*sin(t) + rand(size(t));

%minimize || W*a - [x;y] ||_2
 

i = size(t); % t is a column vector

W=[ones(i) cos(t) zeros(i) zeros(i) ;
zeros(i) zeros(i) ones(i) sin(t) ] ;

%Determine "a" by solving the over determined system:

W*af = [x;y];

%using backslash

af = W \ [x;y]

%Measure the goodness of the fit by looking at the 2-norm of the residual vector:

norm(W*a - [x;y])

%You can also visually check the results:

plot(x,y,'*'); hold on
xnew = af(1) + af(2)*cos(t);
ynew = af(3) + af(4)*sin(t);
plot(xnew, ynew ,'r');